platform :ios, '8.0'

target 'SonomaDemoApp' do
    # React Native
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
        'Core',
        'RCTActionSheet',
        'RCTGeolocation',
        'RCTImage',
        'RCTNetwork',
        'RCTSettings',
        'RCTText',
        'RCTVibration',
        'RCTWebSocket'
    ]

    # Sonoma native SDK dependencies
    pod 'Sonoma', :podspec => 'https://download.hockeyapp.net/sonoma/ios/Sonoma.podspec'

    # React Native wrappers for Sonoma SDK
    pod 'RNSonomaCore', :podspec => '../../RNSonomaCore.podspec' # Will point to github tag
    pod 'RNSonomaAnalytics', :path => '../node_modules/react-native-sonoma-analytics'
    pod 'RNSonomaCrashes', :path => '../node_modules/react-native-sonoma-crashes'
end