target 'SonomaDemoApp' do
    # React Native
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
        'Core',
        'RCTActionSheet',
        'RCTGeolocation',
        'RCTImage',
        'RCTNetwork',
        'RCTSettings',
        'RCTText',
        'RCTVibration',
        'RCTWebSocket'
    ]

    # Sonoma native SDK dependencies
    pod 'AvalancheHub', :path => '../../AvalancheHub.podspec'
    pod 'AvalancheAnalytics', :path => '../../AvalancheAnalytics.podspec'
    pod 'AvalancheErrorReporting', :path => '../../AvalancheErrorReporting.podspec'

    # React Native wrappers for Sonoma SDK
    pod 'RNSonomaHub', :path => '../../RNSonomaHub'
    pod 'RNSonomaAnalytics', :path => '../../RNSonomaAnalytics'
    pod 'RNSonomaErrorReporting', :path => '../../RNSonomaErrorReporting'
end