# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestingSwift' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestingSwift
  pod 'AppCenter/Push', '~> 1.1.0'
  pod 'AppCenter/Crashes', '~> 1.1.0'
  pod 'AppCenter/Analytics', '~> 1.1.0'
  pod 'AppCenterReactNativeShared', :path => '../../AppCenterReactNativeShared/Products/'
end

