# source 'git@github.com:Microsoft/mobile-center-sdk-specs.git'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestApp
  pod 'MobileCenter/Crashes', '~> 0.13.0'
  pod 'MobileCenter/Analytics', '~> 0.13.0'
  pod 'MobileCenter/Push', '~> 0.13.0'
  
  pod 'RNMobileCenterShared', :path => '../../RNMobileCenterShared/Products/'

  platform :ios, '8.0'
end
