# source 'https://msmobilecenter.visualstudio.com/SDK/_git/AppCenterSDK-Specs-Private.git'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestApp' do
  
end
