using System;
using System.Runtime.Serialization;

namespace Microsoft.Azure.Mobile.Crashes
{
    /// <summary>
    /// Exception thrown by <see cref="Crashes.GenerateTestCrash"/>.
    /// </summary>
    [Serializable]
    public class TestCrashException : Exception
    {
        
        const string CrashMessage = "Test crash exception generated by SDK";

        /// <summary>
        /// Initializes a new instance of the TestCrashException class with a predefined error message.
        /// </summary>
        public TestCrashException() : base(CrashMessage)
        {
        }

        /// <summary>
        /// Deserializes data representing a TestCrashException into a new instance of the class.
        /// </summary>
        /// <param name="info">Serialization information for deserialization.</param>
        /// <param name="context">Streaming context for deserialization.</param>
        public TestCrashException(SerializationInfo info, StreamingContext context) : base(info, context) { }
    }
}
