target 'AppCenterReactNativeShared' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppCenterReactNativeShared
  pod 'AppCenter', '~> 2.3.0'

end
