target 'AppCenterReactNativeShared' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppCenterReactNativeShared
  platform :ios, '11.0'
  pod 'AppCenter', '5.0.3'

end
