source 'https://msmobilecenter.visualstudio.com/SDK/_git/AppCenterSDK-Specs-Private'
source 'https://github.com/CocoaPods/Specs.git'

target 'AppCenterReactNativeShared' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppCenterReactNativeShared
  pod 'AppCenter', '4.1.2-6+c0eb1358b885e0ab16c0ae70e4969efed2ecb1bd'

end
