# source 'https://msmobilecenter.visualstudio.com/SDK/_git/AppCenterSDK-Specs-Private.git'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestApp34' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestApp
  pod 'AppCenter/Push', '~> 1.11.0'
  pod 'AppCenter/Crashes', '~> 1.11.0'
  pod 'AppCenter/Analytics', '~> 1.11.0'

  pod 'AppCenterReactNativeShared', :path => '../../AppCenterReactNativeShared/Products/'
  
  platform :ios, '9.0'
end
