# source 'git@github.com:Microsoft/mobile-center-sdk-specs.git'
source 'https://msmobilecenter.visualstudio.com/SDK/_git/AppCenterSDK-Specs-Private' # comment out before release
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestApp34' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestApp
  pod 'AppCenter/Push', '~> 1.0.0-4'
  pod 'AppCenter/Crashes', '~> 1.0.0-4'
  pod 'AppCenter/Analytics', '~> 1.0.0-4'
  pod 'AppCenterReactNativeShared', '~> 1.0.0-1'

  platform :ios, '8.0'
end
