using System;

namespace Microsoft.Sonoma.Xamarin.Crashes
{
    public class TestCrashException : Exception
    {
        private const string CrashMessage = "Test crash exception generated by SDK";

        public TestCrashException(): base(CrashMessage)
        {
        }
    }
}
