# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'newapp' do
  pod 'AppCenter/Push', '~> 2.0.1'
  pod 'AppCenter/Crashes', '~> 2.0.1'
  pod 'AppCenter/Analytics', '~> 2.0.1'
  pod 'AppCenterReactNativeShared', '~> 2.0.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for newapp

  

  platform :ios, '9.0'
  target 'newappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'newapp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for newapp-tvOS

  target 'newapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
