pr:
- master

pool:
  vmImage: macos-latest

variables:
- name: Codeql.Cadence
  value: 0

jobs:
- job:
  displayName: Build and CodeQL DemoApp Android
  steps:
  - checkout: self
    submodules: recursive

  - task: CodeQL3000Init@0
    displayName: CodeQL Initialize

  - task: NodeTool@0
    displayName: 'Use Node 10.x'
    inputs:
      versionSpec: 10.x

  # - task: Npm@1
  #   displayName: 'npm install node-gyp'
  #   inputs:
  #     command: custom
  #     workingDir: DemoApp
  #     verbose: false
  #     customCommand: 'install -g node-gyp'

  - task: Bash@3
    displayName: Run Upgrade-appcenter-npm-packages script
    inputs:
      filePath: DemoApp/upgrade-appcenter-npm-packages.sh
      workingDirectory: DemoApp

  - task: Bash@3
    displayName: Install watchman
    inputs:
      targetType: inline
      script: |
        brew install watchman

  - task: Bash@3
    displayName: Run react-native bundle
    inputs:
      targetType: inline
      script: |
        cd DemoApp/
        npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res

  - task: Gradle@3
    displayName: Build DemoApp
    inputs:
      workingDirectory: DemoApp/android
      tasks: assembleRelease
      publishJUnitResults: false

  - task: CodeQL3000Finalize@0
    displayName: CodeQL Finalize