pr:
- master

pool:
  vmImage: macos-latest

variables:
- name: Codeql.Cadence
  value: 0

jobs:
- job:
  displayName: Build and CodeQL TestApp Android
  steps:
  - checkout: self
    submodules: recursive

  - task: CodeQL3000Init@0
    displayName: CodeQL Initialize

  - task: NodeTool@0
    displayName: 'Use Node 14.x'
    inputs:
      versionSpec: 14.x

  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'
    displayName: 'Use Java 11'

  - task: Bash@3
    displayName: Run update-npm-packages script
    inputs:
      filePath: TestApp/update-npm-packages.sh
      workingDirectory: TestApp
  
  - task: Bash@3
    displayName: Run use-android-manifest-namespaces script
    inputs:
      filePath: TestApp/use-android-manifest-namespaces.sh
      workingDirectory: TestApp

  - task: Bash@3
    displayName: Install watchman
    inputs:
      targetType: inline
      script: |
        brew install watchman

  - task: Gradle@3
    displayName: Build TestApp
    inputs:
      gradleWrapperFile: TestApp/android/gradlew
      workingDirectory: TestApp/android
      tasks: assembleRelease
      publishJUnitResults: false

  - task: CodeQL3000Finalize@0
    displayName: CodeQL Finalize