// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

using System;

namespace Microsoft.AppCenter.Crashes
{
    /// <summary>
    /// Exception type thrown for testing purposes. See <see cref="Crashes.GenerateTestCrash"/>. 
    /// </summary>
    public partial class TestCrashException : Exception
    {
        const string CrashMessage = "Test crash exception generated by SDK";

        /// <summary>
        /// Initializes a new instance of the TestCrashException class with a predefined error message.
        /// </summary>
        public TestCrashException() : base(CrashMessage)
        {
        }
    }
}
